# Generated by Django 5.2 on 2025-04-28 03:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageAnalyzed',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('url', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SimilarityResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('similar_image_id', models.CharField(max_length=255)),
                ('similar_image_url', models.URLField()),
                ('similarity_percentage', models.IntegerField()),
                ('analyzed_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similarities', to='api.imageanalyzed')),
            ],
        ),
    ]
