# Generated by Django 5.2 on 2025-06-02 08:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageComparisonSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SimilarityMetricResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transform_type', models.CharField(choices=[('contrast', 'Contrast'), ('texture', 'Texture'), ('heat_color_map', 'Heat Color Map'), ('hsv_hue', 'HSV Hue'), ('hsv_saturation', 'HSV Saturation'), ('hsv_value', 'HSV Value')], max_length=20)),
                ('similarity_score', models.FloatField()),
                ('file_1', models.CharField(max_length=255)),
                ('file_2', models.CharField(max_length=255)),
                ('comparison', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similarities', to='api.imagecomparisonsession')),
            ],
            options={
                'unique_together': {('comparison', 'transform_type')},
            },
        ),
        migrations.CreateModel(
            name='TransformedImageEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_index', models.IntegerField()),
                ('transform_type', models.CharField(choices=[('contrast', 'Contrast'), ('texture', 'Texture'), ('heat_color_map', 'Heat Color Map'), ('hsv_hue', 'HSV Hue'), ('hsv_saturation', 'HSV Saturation'), ('hsv_value', 'HSV Value')], max_length=20)),
                ('image_url', models.URLField()),
                ('embedding_url', models.URLField()),
                ('filename', models.CharField(max_length=255)),
                ('comparison', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='embeddings', to='api.imagecomparisonsession')),
            ],
            options={
                'unique_together': {('comparison', 'image_index', 'transform_type')},
            },
        ),
    ]
