# Generated by Django 5.2.7 on 2025-10-10 07:31

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageComparisonSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SimilarityMetricResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transform_type', models.CharField(choices=[('contrast', 'Contrast'), ('texture', 'Texture'), ('heat_color_map', 'Heat Color Map'), ('hsv_hue', 'HSV Hue'), ('hsv_saturation', 'HSV Saturation'), ('hsv_value', 'HSV Value')], max_length=20)),
                ('similarity_score', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('file_1', models.CharField(max_length=255)),
                ('file_2', models.CharField(max_length=255)),
                ('comparison', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similarities', to='transformations.imagecomparisonsession')),
            ],
            options={
                'unique_together': {('comparison', 'transform_type')},
            },
        ),
        migrations.CreateModel(
            name='TransformedImageEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_index', models.PositiveIntegerField(help_text='1 for the first image, 2 for the second image.', verbose_name='Image Index')),
                ('transform_type', models.CharField(choices=[('original_image', 'Original'), ('color', 'Color'), ('contrast', 'Contraste'), ('texture', 'Textura'), ('brush', 'Pincel'), ('heatmap', 'Mapa de calor')], default='original_image', max_length=50)),
                ('image_url', models.URLField()),
                ('embedding_url', models.URLField()),
                ('filename', models.CharField(max_length=255)),
                ('comparison', models.ForeignKey(help_text='The comparison session this transformed image embedding belongs to.', on_delete=django.db.models.deletion.CASCADE, to='transformations.imagecomparisonsession', verbose_name='Comparison Session')),
            ],
            options={
                'unique_together': {('comparison', 'image_index', 'transform_type')},
            },
        ),
    ]
