services:
  transform:
    container_name: service-transform
    build:
      context: .
      dockerfile: Dockerfile
    command: uvicorn app.main:app --host 0.0.0.0 --port 8001
    ports:
      - "5001:8001"
    # env_file:
    #   - .env # guardar variables (recomendado)
    # environment:
    #   # Si no usas .env, define aquí (no hardcode en código)
    #   CLOUDINARY_CLOUD_NAME: ${CLOUDINARY_CLOUD_NAME}
    #   CLOUDINARY_API_KEY: ${CLOUDINARY_API_KEY}
    #   CLOUDINARY_API_SECRET: ${CLOUDINARY_API_SECRET}
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD",
          "python",
          "-c",
          "import urllib.request as u; u.urlopen('http://127.0.0.1:8001/docs')",
        ]
      interval: 10s
      timeout: 3s
      retries: 10
    networks:
      - art_net

networks:
  art_net:
    name: art_net
